"""
NicksPizza
Project Euler .net

Even Fibonacci numbers
Problem 2

Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.

Answer: 4613732
"""


# 1
def euler_two(upper_limit):
    a = 1
    b = 1
    c = a + b
    sums = 0
    while c < upper_limit:

        sums += c
        a = b + c
        b = a + c
        c = a + b
    return sums
